#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" sudo tee -a /etc/default/haproxy
sudo echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web_back
backend web_back
	balance roundrobin
	server 1857-web-01 35.196.95.205:80 check
	server 1857-web-02 34.73.121.54:80 check
" sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
