#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.
echo $$ > /var/run/holbertonscript.pid
while :
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo 'i hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
    trap "echo 'Y U no love me?!'" SIGINT
    trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
done
