#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
# http://www.sromero.org/wiki/linux/aplicaciones/uso_de_awk
awk '{ print $1 " " $9 }' apache-access.log
